export const DashboardLocators = {
    dashboardLeftMenuBtn: "//div[@role='button']//span[text()='Dashboard']",
    additionalRequestsSelect: "//div[text()='Additional Requests']",
    options: "//ul[@role='listbox']",
    eventsSelect:"//div[text()='Events']",
    adminSelectTxt: "(//input[@role='combobox'])[1]",    
    firstNameTxt: "//input[@name='firstName']",
    secondNameTxt: "//input[@name='middleName']",
    thirdNameTxt: "//input[@name='thirdName']",
    fourthNameTxt: "//input[@name='fourthName']",
    lastNameTxt: "//input[@name='lastName']",
    nationalitySelectTxt: "//label[text()='Nationality']/following-sibling::div//input[@role='combobox']",    
    passportQidTxt: "//input[@name='documentNumber']",
    emailAddressTxt: "//input[@name='email']",
    contactNumberTxt: "//input[@name='contact']",
    dobTxt: "//label[text()='Date of Birth *']/following-sibling::div/input",
    submitBtn: "//button[text()='Submit']",
    cancelBtn: "//button[text()='Cancel']",
    visaQuota_selectVisaTypeSelect: "//div[text()='Select Visa Type(s)']",
    visaQuota_noOfVisaTxt: "//input[@placeholder='Number of Visas']",
    newVisaSer_selectVisaTypeSelect: "//div[text()='Select Visa Type']",
    newVisaSer_noOfVisaTxt: "//input[@placeholder='No of Visas']",
    addBtn: "button svg[data-testid='AddCircleOutlineIcon']",
    hmpRadioBtn: "//input[@value='HMP' and @type='radio']",
    hacsRadioBtn: "//input[@value='HACS' and @type='radio']",
    proceedBtn: "//button[text()='Proceed']",
    passportQidDoc: "#file-upload",
};