export const EventsLocators = {
    eventLeftMenu: "//div[@role='button']//span[text()='Events']",
    addEventBtn: "//button[text()='Add Event']",
    eventNameTxt: "//input[@name='name']",
    eventNameValidationTxt: "//input[@name='name']/parent::div/following-sibling::p",
    eventVisaQtnTxt: "//input[@name='requiredQtyEventVisa']",
    eventVisaQtnValidationTxt: "//input[@name='requiredQtyEventVisa']/parent::div/following-sibling::p",
    eventStartDateTxt: "//label[contains(text(),'Event Start Date')]/following-sibling::div/input",
    eventStartDateValidationTxt: "//label[contains(text(),'Event Start Date')]/parent::div/p",
    eventEndDateTxt: "//label[contains(text(),'Event End Date')]/following-sibling::div/input",
    eventEndDateValidationTxt: "//label[contains(text(),'Event End Date')]/parent::div/p",
    eventLocationTxt: "//label[contains(text(),'Event Location')]/following-sibling::div/input",    
    eventLocationValidationTxt: "//label[contains(text(),'Event Location')]/parent::div/p",
    eventDetailsTxt: "//label[contains(text(),'Event Details')]/following-sibling::div//input",
    eventDetailsValidationTxt: "//label[contains(text(),'Event Details')]/parent::div//p",
    applicantArrivalDateTxt: '//label[contains(text(),"Applicant\'s Arrival Date")]/following-sibling::div/input',
    applicantArrivalDateValidationTxt: '//label[contains(text(),"Applicant\'s Arrival Date")]/parent::div/p',
    applicantDepartureDateTxt: '//label[contains(text(),"Applicant\'s Departure Date")]/following-sibling::div/input',
    applicantDepartureDateValidationTxt: '//label[contains(text(),"Applicant\'s Departure Date")]/following-sibling::div/following-sibling::p',
    eventStartTimeTxt: "//label[contains(text(),'Event Start Time')]/following-sibling::div/input",
    eventStartTimeValidationTxt: "//label[contains(text(),'Event Start Time')]/parent::div/p",
    eventEndTimeTxt: "//label[contains(text(),'Event End Time')]/following-sibling::div/input",
    eventEndTimeValidationTxt: "//label[contains(text(),'Event End Time')]/parent::div/p",
    natureOfEventSelectTxt: "//label[contains(text(),'Nature of Event')]/following-sibling::div",
    natureOfEventValidationTxt: "//input[@name='eventTypeId']/parent::div/following-sibling::p",
    specifyNatureOfEventTxt: "//label[contains(text(),'Specify Event Nature')]/following-sibling::div/input",
    specifyNatureOfEventValidationTxt: "//label[contains(text(),'Specify Event Nature')]/following-sibling::p",
    sponsoringEntityTxt: "#sponsoring-entity",
    sponsoringEntityValidationTxt: "//input[@id='sponsoring-entity']/parent::div/following-sibling::p",
    authenticateDegreeUpload: "#upload_authenticateddegree",
    authenticatedDegreeValidationTxt: "//input[@id='upload_authenticateddegree']/parent::div/p",
    cvUpload: "#upload_cv",    
    cvValidationTxt: "//input[@id='upload_cv']/parent::div/p",
    authorizerLetterUpload: "#upload_authorizerletter",
    authorizerLetterValidationTxt: "//input[@id='upload_authorizerletter']/parent::div/p",
    establishmentCardUpload: "#upload_establishmentcardimage",
    establishmentCardValidationTxt: "//input[@id='upload_establishmentcardimage']/parent::div/p",
    policeClearanceCertificateUpload: "#upload_policeclearancefromcountryofresidence",
    policeClearanceCertificateValidationTxt: "//input[@id='upload_policeclearancefromcountryofresidence']/parent::div/p",
    sectoralEndoresementUpload: "#upload_sectoralendorsementletter",
    sectoralEndoresementValidationTxt: "//input[@id='upload_sectoralendorsementletter']/parent::div/p",
    backBtn: "//button[text()='Back']",
    nextBtn: "//button[text()='Next']",
    conferenceVisaCheckbox: "//span[text()='Conference & Event Visa']/preceding-sibling::span/input",
    privateEventCheckbox: "//span[text()='Private Event Visa']/preceding-sibling::span/input",
    hmpCheckbox: "//span[text()='Hayya Media Portal']/ancestor::label//input",
    accredAndPermitCheckbox: "//span[text()='Accreditation and Permits']/ancestor::label//input",

    peakAppSubmissionPeriodTxt: "//label[text()='Expected Peak Period of Application Submission *']/following-sibling::div/input",
    plannedAppStartDateTxt: "//label[contains(text(),'Planned Application Start Date')]/following-sibling::div/input",
    plannedAppStartDateTxtValdiation: "//label[contains(text(),'Planned Application Start Date')]/parent::div/p",
    plannedAppEndDateTxt: "//label[contains(text(),'Planned Application End Date')]/following-sibling::div/input",
    plannedAppEndDateTxtValidation: "//label[contains(text(),'Planned Application End Date')]/parent::div/p",
    requiredMediaApplicationsTxt: "//label[contains(text(),'Required Number of Media Applications')]/following-sibling::div/input",

    filmPermitStartDateTxt: "//label[contains(text(),'Film Permit Start Date')]/following-sibling::div/input",
    filmPermitStartDateTxtValidation: "//label[contains(text(),'Film Permit Start Date')]/parent::div/p",

    filmPermitEndDateTxt: "//label[contains(text(),'Film Permit End Date')]/following-sibling::div/input",
    filmPermitEndDateTxtValidation: "//label[contains(text(),'Film Permit End Date')]/parent::div/p",

    adminFirstNameTxt: "//label[contains(text(),'First Name')]/following-sibling::div/input",
    adminMiddleNameTxt: "//label[text()='Middle Name']/following-sibling::div/input",
    adminThirdNameTxt: "//label[text()='Third Name']/following-sibling::div/input",
    adminFourthNameTxt: "//label[text()='Fourth Name']/following-sibling::div/input",
    adminLastNameTxt: "//label[contains(text(),'Last Name')]/following-sibling::div/input",
    adminNationalitySelectTxt: "//div[contains(text(),'Select Nationality')]",
    options: "//ul[@role='listbox']//li[@role='option']",
    adminPassportQidTxt: "//label[contains(text(),'Passport/QID Number')]/following-sibling::div/input",
    adminPassportQidDoc: "//label[contains(text(),'Passport Document')]/following-sibling::div//input[@type='file']",
    adminEmailAddressTxt: "//label[contains(text(),'Email Address')]/following-sibling::div/input",
    adminContactNumberTxt: "//label[contains(text(),'Contact Number')]/following-sibling::div/input",

    submitApplicationBtn: "//button[text()='Submit Application']",
    continueBtn: "//button[text()='Continue']",
    eventTable: "//table"





};