
export const RegisterOrganizationLocators = {
    registerOrgBtn: "//button[text()='Register your Organization']",
    orgNameTxt: "//label[text()='Organization *']/parent::div/div/input",
    orgNameValidation: "//label[text()='Organization *']/following::div/input",
    establishmentNoTxt: "//label[text()='Establishment No. *']/parent::div/div/input",
    establishmentNoValidation: "//label[text()='Establishment No. *']/parent::div/p",
    establishmentExpDateTxt: "//label[text()='Establishment Card Expiry Date*']/parent::div/div/input",
    establishmentExpDateValdiation: "//label[text()='Establishment Card Expiry Date*']/parent::div/p",
    requestorNameTxt: "//label[text()='Requestor Name *']/parent::div/div/input",    
    requestorNameValidation: "//label[text()='Requestor Name *']/parent::div/p",
    jobTitleTxt: "//div[text()='Job Title *']/parent::div/div/input",
    jobTitleValidation: "//div[text()='Job Title *']/ancestor::div[3]/following-sibling::p",
    requestorNationalitySelect: '//div[text()="Requestor\'s Nationality *"]/parent::div/div/input',
    requestorNationalitySelectValdiaiton: '//div[text()="Requestor\'s Nationality *"]/ancestor::div[3]/following-sibling::p',
    requestorsQatarIDTxt: '//label[text()="Requestor\'s QID Number *"]/parent::div/div/input',
    requestorsQatarIDValdiation: '//label[text()="Requestor\'s QID Number *"]/parent::div/p',
    requestorDobTxt: "//label[text()='Requestor Date of Birth*']/parent::div/div/input",
    requestorDobValidation: "//label[text()='Requestor Date of Birth*']/parent::div/p",
    requestorsEmailAdddressTxt: '//label[text()="Requestor\'s Email Address *"]/parent::div/div/input',    
    requestorsContactNumTxt: '//label[text()="Requestor\'s Contact Number *"]/parent::div/div//input',
    requestorsContactNumValidation: '//label[text()="Requestor\'s Contact Number *"]/parent::div/p',
    orgAuthorizedSignatoryNameTxt: '//label[text()="Organization\'s Authorized Signatory Name *"]/parent::div/div//input',
    orgAuthorizedSignatoryNameValidation: '//label[text()="Organization\'s Authorized Signatory Name *"]/parent::div/p',
    signatoryQatarIDTxt: "//label[text()='Signatory QID *']/parent::div/div//input",
    signatoryQatarIDValidation: "//label[text()='Signatory QID *']/parent::div/p",    
    signatoryContactNumTxt: "//label[text()='Signatory Contact No *']/parent::div/div//input",
    signatoryContactNumValidation: "//label[text()='Signatory Contact No *']/parent::div//p",
    authorizerLetterUpload: "#upload_authorizerletter",
    authorizerLetterUploadValidation: "//input[@id='upload_authorizerletter']/parent::div/p",
    establishmentCardUpload: "#upload_uploadestablishmentcardimage",
    establishmentCardUploadValidation: "//input[@id='upload_establishmentcardimage']/parent::div/p",
    verifyBtn: "//button[text()='Verify']",
};